# Dependencies
markdown:         redcarpet
redcarpet:
  extensions      : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            AndyYang
tagline:          'A tagline theme'
description:      '貓貓狗狗玩樂搗蛋散步的地方 <img src="public/favicon.ico" alt="">'
url:              http://andy88566y.github.io
baseurl:          /

author:
  name:           'Andy Yang'
  url:            https://facebook/GCDFromTaiwan

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/andy88566y/andy88566y.github.io

# Gems
plugins: [jekyll-paginate]
plugins: [jekyll-gist]
